### ISSUE TITLE
Create a way to download stock price information as a ".csv"

### ISSUE THREAD

**Issue by kunalJa** [kunalJa/461L-Stock-Project#14]
It would be really useful if we were able to download stock price information for a particular stock in a _.csv_ format in the following structure:
    symbol, date, price

**Comment by Balakumaran-Bala** [comment]
Now you can download the csv in that exact format !!

**Comment by kunalJa** [comment]
Hey Bala I am updating the component you added to save the file with a particular file-name as opposed to the default file name provided by the component!
